### ISSUE TITLE
any? method works wrong

### ISSUE THREAD

**Issue by the-teacher** [TheRole/TheRoleApi#3]
strange. my expectations was broken
method `any?` works wrong. And I think, tests works wrong too.

it should be changed from

```ruby
@role.any?({ pages: :index, pages: :update})
```
to

```ruby
@role.any?({ pages: [:index, :update] })
```

**Comment by sedx** [comment]
https://github.com/TheRole/TheRoleApi/pull/4
https://github.com/TheRole/DummyApp/pull/3

**Comment by the-teacher** [comment]
https://travis-ci.org/TheRole/DummyApp/builds/48399073
